[feature] Added dedicated celery queues #166
openwisp/docker-openwisp pull request #208
Opened 2022-04-01 14:57 UTC by pandafy

Closes #166

**TODO**
- [x] Documentation

2022-04-01 16:06 UTC, nemesisdesign reviewed
The build is faling, aren't you getting the same issue locally?

2022-04-01 16:06 UTC, nemesisdesign commented on build/common/init_command.sh
> +    celery -A openwisp worker -l ${DJANGO_LOG_LEVEL} --queues celery -n background@%%h --logfile /opt/openwisp/logs/celery_background.log --pidfile /opt/openwisp/celery_background.pid --detach
the celery_background name may be misleading because openwisp-radius periodic tasks will end up here too

2022-04-01 16:06 UTC, nemesisdesign commented on build/common/init_command.sh
> +    sleep 1s
why there's a sleep here but not in the `celery_monitoring` section?

2022-04-02 17:53 UTC, nemesisdesign reviewed
Please rebase on the latest master.

2022-04-04 16:04 UTC, nemesisdesign commented on tests/runtests.py
> +            self.fail(f'All celery works are not online: {online_workers}')
works > worker

2022-04-04 23:53 UTC, nemesisdesign requested changes
I tried setting up a device and assign a management_ip to it but it's not being monitored.

Please ensure the expected outcome is met:

- devices are monitored
- checks for new devices are created
- firmware upgrade tasks are started as expected
- periodic radius and notification management tasks are executed as expected

Don't forget to update the README as dicussed.

2022-04-04 23:53 UTC, nemesisdesign commented on build/common/openwisp/celery.py
> +        'monitoring-periodic-task': {
can we name this just `run_checks` for [consistency with ansible-openwisp2](https://github.com/openwisp/ansible-openwisp2/blob/master/templates/openwisp2/settings.py#L231)?

BTW, is this scheduled used anywhere at all?

2022-04-05 13:19 UTC, pandafy commented
Miro board link https://miro.com/app/board/uXjVO_H0D9A=/?invite_link_id=270385425827

cc @atb00ker

2022-04-05 23:02 UTC, nemesisdesign requested changes
All good except the typo below.

2022-04-06 16:17 UTC, nemesisdesign requested changes

2022-04-06 16:17 UTC, nemesisdesign commented on build/common/init_command.sh
> +        tail -f /opt/openwisp/logs/*
can you please break the long lines here with a backslash to improve readability?

eg: 

```
celery -A openwisp worker -l ${DJANGO_LOG_LEVEL} --queues monitoring \
       -n monitoring@%h --logfile /opt/openwisp/logs/celery_monitoring.log \
       --pidfile /opt/openwisp/celery_monitoring.pid --detach
```

2022-04-06 17:20 UTC, nemesisdesign approved these changes

2022-04-06 17:20 UTC, merged